class ColmexProOrdersCSVColumns:
    ACCOUNT = "Account"
    TRADE_DATE = "Trade Date"
    CURRENCY = "Currency"
    ACCOUNT_TYPE = "Account Type"
    SIDE = "Side"
    SYMBOL = "Symbol"
    SHARES = "Shares"
    PRICE = "Price"
    EXEC_TIME = "Exec Time"
    COMMISSION = "Commission"
    SEC_FEE = "SEC Fee"
    TAF_FEE = "TAF Fee"
    ECN_FEE = "ECN Fee"
    ROUTING_FEE = "Routing Fee"
    NSCC_FEE = "NSCC Fee"
    CLR_TYPE = "Clr Type"
    CLR_BROKER = " Clr Broker"
    NOTE = "Note"

    # Calculated columns
    ROW_NUMBER = ""
    DATETIME = "DateTime"
    POSITION = "Position"
    QUANTITY = "Quantity"
    AMOUNT = "Amount"
